namespace EnzoCommanderSDK.Models
{
    public class Customer
    {
        public string timestamp { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public string SearchName { get; set; }
        public string Name2 { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string PhoneNo { get; set; }
        public string TelexNo { get; set; }
        public string OurAccountNo { get; set; }
        public string TerritoryCode { get; set; }
        public string GlobalDimension1Code { get; set; }
        public string GlobalDimension2Code { get; set; }
        public string ChainName { get; set; }
        public string BudgetedAmount { get; set; }
        public string CreditLimitLCY { get; set; }
        public string CustomerPostingGroup { get; set; }
        public string CurrencyCode { get; set; }
        public string CustomerPriceGroup { get; set; }
        public string LanguageCode { get; set; }
        public string StatisticsGroup { get; set; }
        public string PaymentTermsCode { get; set; }
        public string FinChargeTermsCode { get; set; }
        public string SalespersonCode { get; set; }
        public string ShipmentMethodCode { get; set; }
        public string ShippingAgentCode { get; set; }
        public string PlaceofExport { get; set; }
        public string InvoiceDiscCode { get; set; }
        public string CustomerDiscGroup { get; set; }
        public string CountryRegionCode { get; set; }
        public string CollectionMethod { get; set; }
        public string Amount { get; set; }
        public string Blocked { get; set; }
        public string InvoiceCopies { get; set; }
        public string LastStatementNo { get; set; }
        public string PrintStatements { get; set; }
        public string BilltoCustomerNo { get; set; }
        public string Priority { get; set; }
        public string PaymentMethodCode { get; set; }
        public string LastDateModified { get; set; }
        public string ApplicationMethod { get; set; }
        public string PricesIncludingVAT { get; set; }
        public string LocationCode { get; set; }
        public string FaxNo { get; set; }
        public string TelexAnswerBack { get; set; }
        public string VATRegistrationNo { get; set; }
        public string CombineShipments { get; set; }
        public string GenBusPostingGroup { get; set; }
        public string Picture { get; set; }
        public string PostCode { get; set; }
        public string County { get; set; }
        public string EMail { get; set; }
        public string HomePage { get; set; }
        public string ReminderTermsCode { get; set; }
        public string NoSeries { get; set; }
        public string TaxAreaCode { get; set; }
        public string TaxLiable { get; set; }
        public string VATBusPostingGroup { get; set; }
        public string Reserve { get; set; }
        public string BlockPaymentTolerance { get; set; }
        public string ICPartnerCode { get; set; }
        public string Prepayment { get; set; }
        public string PrimaryContactNo { get; set; }
        public string ResponsibilityCenter { get; set; }
        public string ShippingAdvice { get; set; }
        public string ShippingTime { get; set; }
        public string ShippingAgentServiceCode { get; set; }
        public string ServiceZoneCode { get; set; }
        public string AllowLineDisc { get; set; }
        public string BaseCalendarCode { get; set; }
        public string CopySelltoAddrtoQteFrom { get; set; }
        public string CustomerType { get; set; }
        public string CustomerInstructions { get; set; }
        public string BankCommunication { get; set; }
        public string CheckDateFormat { get; set; }
        public string CheckDateSeparator { get; set; }
        public string CustomerStatus { get; set; }
        public string CreationDate { get; set; }
        public string MDM { get; set; }
        public string TaxExemptionNo { get; set; }
        public string EUDeclaration { get; set; }
        public string FDALetter { get; set; }
        public string ExpirationDateBuffer { get; set; }
        public string TaxIdentificationType { get; set; }
        public string VATExempt { get; set; }
        public string LiqPaymentTermsCode { get; set; }
        public string EDIInvoice { get; set; }
        public string EDITradePartner { get; set; }
        public string EDIInternalDocNo { get; set; }
        public string EffectiveDate { get; set; }
        public string ChangeDate { get; set; }
        public string EShipAgentService { get; set; }
        public string FreeFreight { get; set; }
        public string ResidentialDelivery { get; set; }
        public string IRSEINNumber { get; set; }
        public string BlindShipment { get; set; }
        public string DoubleBlindShipment { get; set; }
        public string DoubleBlindShipfromCustNo { get; set; }
        public string NoFreeFreightLinesonOrder { get; set; }
        public string ShippingPaymentType { get; set; }
        public string ShippingInsurance { get; set; }
        public string ExternalNo { get; set; }
        public string DefaultShipforCode { get; set; }
        public string PackingRuleCode { get; set; }
        public string EMailRuleCode { get; set; }
        public string EMailCustStatSendDate { get; set; }
        public string UseEMailRuleforShipToAddr { get; set; }
        public string FederalIDNo { get; set; }
        public string IdentificationNo { get; set; }
        public string IdentificationState { get; set; }
        public string EFTFraudProtectionStatus { get; set; }
        public string DoNotSaveCreditCardNos { get; set; }
        public string DoNotSaveCheckingActNos { get; set; }
        public string SearchEMail { get; set; }
        public string ElectronicInvoiceType { get; set; }
        public string LastClicktoPayStmtURL { get; set; }
        public string LastClicktoPayStmtDate { get; set; }
        public string SyncwithConnect { get; set; }
        public string HardCopyRequired { get; set; }
        public string APContact { get; set; }
        public string APPhoneNo { get; set; }
        public string APEmail { get; set; }
        public string AutomatedInvoiceType { get; set; }
        public string InventoryInquiryType { get; set; }
        public string EDIVendorNo { get; set; }
        public string InvoiceEDIPortCode { get; set; }
        public string CrMemoEDIPortCode { get; set; }
        public string ShipmentEDIPortCode { get; set; }
        public string ChangeAckEDIPortCode { get; set; }
        public string AcknowledgmentEDIPortCode { get; set; }
        public string InvInquiryEDIPortCode { get; set; }
        public string InventoryInquiryNos { get; set; }
        public string InvInquiryLocationFilter { get; set; }
        public string LastInvInquiryEntryNo { get; set; }
        public string LastInvInqItemEntryNo { get; set; }
        public string LastInvInqDateTime { get; set; }
        public string RequireShiptoCode { get; set; }
        public string DutiesAccountNo { get; set; }
        public string ELSShippingPaymentType { get; set; }
        public string ELS3rdPartyShipAccountNo { get; set; }
        public string ELSShippingInsurance { get; set; }
        public string AccountType { get; set; }
        public string LoadFileName { get; set; }
        public DateTime LoadFileDate { get; set; }
    }

}
